server:
  port: 8090
  
spring:
  application:
    name: "cloudgateway"
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://localhost:8091/
          predicates:
            - Path=/resource1/**
          filters:
            - SetPath=/resourceserver01/  
        - id: route2
          uri: http://localhost:8092/
          predicates:
            - Path=/resource2/**
          filters:
            - SetPath=/resourceserver02/